//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peer2PeerChat.ChatServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceClient.IChatService")]
    public interface IChatService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Hello")]
        void Hello(System.Uri address, string nick, string mac_hash);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Hello")]
        System.Threading.Tasks.Task HelloAsync(System.Uri address, string nick, string mac_hash);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Chat")]
        void Chat(string message, string mac_hash);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Chat")]
        System.Threading.Tasks.Task ChatAsync(string message, string mac_hash);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Bye")]
        void Bye(string mac_hash);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Bye")]
        System.Threading.Tasks.Task ByeAsync(string mac_hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceChannel : Peer2PeerChat.ChatServiceClient.IChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceClient : System.ServiceModel.ClientBase<Peer2PeerChat.ChatServiceClient.IChatService>, Peer2PeerChat.ChatServiceClient.IChatService {
        
        public ChatServiceClient() {
        }
        
        public ChatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Hello(System.Uri address, string nick, string mac_hash) {
            base.Channel.Hello(address, nick, mac_hash);
        }
        
        public System.Threading.Tasks.Task HelloAsync(System.Uri address, string nick, string mac_hash) {
            return base.Channel.HelloAsync(address, nick, mac_hash);
        }
        
        public void Chat(string message, string mac_hash) {
            base.Channel.Chat(message, mac_hash);
        }
        
        public System.Threading.Tasks.Task ChatAsync(string message, string mac_hash) {
            return base.Channel.ChatAsync(message, mac_hash);
        }
        
        public void Bye(string mac_hash) {
            base.Channel.Bye(mac_hash);
        }
        
        public System.Threading.Tasks.Task ByeAsync(string mac_hash) {
            return base.Channel.ByeAsync(mac_hash);
        }
    }
}
